apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: Azure-03-dev

resources:
  - ../../base
  - namespace.yaml

commonLabels:
  environment: dev
  app.kubernetes.io/part-of: Azure-03

# Environment-specific patches
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

# Environment-specific config
configMapGenerator:
  - name: Azure-03-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
