apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: AKS-01
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /AKS-01
        pathType: Prefix
        backend:
          service:
            name: AKS-01
            port:
              number: 80
