apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: Azure-03

resources:
  - kibana.yaml

commonLabels:
  app.kubernetes.io/part-of: Azure-03
  app.kubernetes.io/component: kibana
  app.kubernetes.io/managed-by: eck
