apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: Azure-02-dev
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: Azure-02
  path: ./overlays/dev
  prune: true
  wait: true
  timeout: 2m
