apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: Azure-02

resources:
  - namespace.yaml
  - cluster.yaml

commonLabels:
  app.kubernetes.io/part-of: Azure-02
  app.kubernetes.io/component: elasticsearch
  app.kubernetes.io/managed-by: eck
