apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: Azure-02-production
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: Azure-02
  path: ./overlays/production
  prune: true
  wait: true
  timeout: 5m
