apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: Azure-02
  app.kubernetes.io/managed-by: argocd

resources:
  # Add your base resources here
  # - deployment.yaml
  # - service.yaml
  # - configmap.yaml

# ConfigMap generator
configMapGenerator:
  - name: Azure-02-config
    literals:
      - APP_NAME=Azure-02
