apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: AKS-04

resources:
  - kibana.yaml

commonLabels:
  app.kubernetes.io/part-of: AKS-04
  app.kubernetes.io/component: kibana
  app.kubernetes.io/managed-by: eck
