apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: Azure-02

resources:
  - rbac.yaml
  - fleet-server.yaml
  - elastic-agent.yaml

commonLabels:
  app.kubernetes.io/part-of: Azure-02
  app.kubernetes.io/component: agents
  app.kubernetes.io/managed-by: eck
