apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Azure-02
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /Azure-02
        pathType: Prefix
        backend:
          service:
            name: Azure-02
            port:
              number: 80
