apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: AKS-01-dev
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: AKS-01
  path: ./overlays/dev
  prune: true
  wait: true
  timeout: 2m
