apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: AKS-04

resources:
  - namespace.yaml
  - cluster.yaml

commonLabels:
  app.kubernetes.io/part-of: AKS-04
  app.kubernetes.io/component: elasticsearch
  app.kubernetes.io/managed-by: eck
